version: 0.0

os: linux

files:
     - source: /
       destination: /var/www/html
hooks:
      ApplicationStop:
        - location: scripts/stop-server.sh
          timeout: 300
          runas: ubuntu     
      BeforeInstall:
        - location: scripts/install-dependencies.sh
          timeout: 300
          runas: ubuntu
      AfterInstall:
        - location: scripts/change-permissions.sh
          timeout: 300
          runas: ubuntu
      ApplicationStart:
        - location: scripts/start-server.sh
          timeout: 300
          runas: ubuntu
      ValidateService:
        - location: scripts/validate-server.sh
          timeout: 300
          runas: ubuntu
